Fish.create!(name: "赤魚", line: "あ", n3_oil: 0.23, vitamin_a: 26, mercury: nil, content: "", image: "")
Fish.create!(name: "アジ", line: "あ", n3_oil: 1.05, vitamin_a: 7, mercury: nil, content: "1匹 70g", image: "")
Fish.create!(name: "穴子", line: "あ", n3_oil: 1.42, vitamin_a: 500, mercury: nil, content: "", image: "")
Fish.create!(name: "アユ", line: "あ", n3_oil: 0.82, vitamin_a: 55, mercury: nil, content: "1匹 80g", image: "")
Fish.create!(name: "あんこう", line: "あ", n3_oil: 0.03, vitamin_a: 13, mercury: nil, content: "鍋用1片 50g", image: "")
Fish.create!(name: "あんこう 肝", line: "あ", n3_oil: 100, vitamin_a: 8300, mercury: nil, content: "あん肝1切 20g", image: "")
Fish.create!(name: "イルカ(ｲｼｲﾙｶ)", line: "い", n3_oil: 0, vitamin_a: 0, mercury: 62.5, content: "", image: "")
Fish.create!(name: "イルカ(ﾊﾞﾝﾄﾞｳｲﾙｶ)", line: "い", n3_oil: 0, vitamin_a: 0, mercury: 1000, content: "", image: "")
Fish.create!(name: "イシイルカ", line: "い", n3_oil: 0, vitamin_a: 0, mercury: 62.5, content: "", image: "")
Fish.create!(name: "バンドウイルカ", line: "は", n3_oil: 0, vitamin_a: 0, mercury: 1000, content: "", image: "")
Fish.create!(name: "いわし", line: "い", n3_oil: 2.10, vitamin_a: 8, mercury: nil, content: "1匹 50g", image: "")
Fish.create!(name: "しらす", line: "し", n3_oil: 0.49, vitamin_a: 140, mercury: nil, content: "", image: "")
Fish.create!(name: "いわし 缶詰", line: "い", n3_oil: 2.92, vitamin_a: 9, mercury: nil, content: "", image: "")
Fish.create!(name: "うなぎ", line: "う", n3_oil: 2.87, vitamin_a:1500, mercury: nil, content: "蒲焼1切 50g", image: "")
Fish.create!(name: "うなぎ 肝", line: "う", n3_oil: 0.79, vitamin_a: 4400, mercury: nil, content: "1個 10g", image: "")
Fish.create!(name: "カジキ(ﾏｶｼﾞｷ)", line: "か", n3_oil: 0.44, vitamin_a: 8, mercury: 62.5, content: "高級魚。スーパーでは「メカジキ」の方が多い", image: "")
Fish.create!(name: "カジキ(ﾒｶｼﾞｷ)", line: "か", n3_oil: 0.92, vitamin_a: 61, mercury: 125, content: "", image: "")
Fish.create!(name: "マカジキ", line: "ま", n3_oil: 0.44, vitamin_a: 8, mercury: 62.5, content: "高級魚。スーパーでは「メカジキ」の方が多い", image: "")
Fish.create!(name: "メカジキ", line: "め", n3_oil: 0.92, vitamin_a: 61, mercury: 125, content: "", image: "")
Fish.create!(name: "かつお(春獲り)", line: "か", n3_oil: 0.17, vitamin_a: 5, mercury: nil, content: "", image: "")
Fish.create!(name: "かつお(秋獲り)", line: "か", n3_oil: 1.57, vitamin_a: 20, mercury: nil, content: "", image: "")
Fish.create!(name: "かつお 缶詰", line: "か", n3_oil: 1.99, vitamin_a: 0, mercury: nil, content: "", image: "")
Fish.create!(name: "かれい", line: "か", n3_oil: 0.35, vitamin_a: 5, mercury: nil, content: "", image: "")
Fish.create!(name: "カンパチ", line: "か", n3_oil: 1.07, vitamin_a: 4, mercury: nil, content: "", image: "")
Fish.create!(name: "きす", line: "き", n3_oil: 0.05, vitamin_a: 1, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(銀ﾀﾞﾗ)", line: "た", n3_oil: 1.13, vitamin_a: 1500, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(ﾏﾀﾞﾗ)", line: "た", n3_oil: 0.07, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(ｽｹﾄｳﾀﾞﾗ)", line: "た", n3_oil: 0.25, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "銀だら", line: "き", n3_oil: 1.13, vitamin_a: 1500, mercury: nil, content: "", image: "")
Fish.create!(name: "鯛(ｷﾀﾞｲ)", line: "た", n3_oil: 0.57, vitamin_a: 50, mercury: 62.5, content: "", image: "")
Fish.create!(name: "鯛(ｷﾝﾒﾀﾞｲ)", line: "た", n3_oil: 1.37, vitamin_a: 63, mercury: 125, content: "", image: "")
Fish.create!(name: "キダイ", line: "き", n3_oil: 0.57, vitamin_a: 50, mercury: 62.5, content: "", image: "")
Fish.create!(name: "金目鯛", line: "き", n3_oil: 1.37, vitamin_a: 63, mercury: 125, content: "", image: "")
Fish.create!(name: "クジラ(ﾂﾁｸｼﾞﾗ)", line: "く", n3_oil: 0, vitamin_a: 0, mercury: 125, content: "", image: "")
Fish.create!(name: "クジラ(ﾏｯｺｳｸｼﾞﾗ)", line: "く", n3_oil: 0, vitamin_a: 0, mercury: 125, content: "", image: "")
Fish.create!(name: "ツチクジラ", line: "つ", n3_oil: 0, vitamin_a: 0, mercury: 125, content: "", image: "")
Fish.create!(name: "マッコウクジラ", line: "ま", n3_oil: 0, vitamin_a: 0, mercury: 125, content: "", image: "")
Fish.create!(name: "鮭(銀鮭)", line: "さ", n3_oil: 2.03, vitamin_a: 36, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(ｱﾄﾗﾝﾃｨｯｸｻｰﾓﾝ)", line: "さ", n3_oil: 1.94, vitamin_a: 14, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(ﾄﾗｳﾄｻｰﾓﾝ・ﾆｼﾞﾏｽ)", line: "さ", n3_oil: 2.56, vitamin_a: 57, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(紅鮭)", line: "さ", n3_oil: 0.92, vitamin_a: 27, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(ｷﾝｸﾞｻｰﾓﾝ)", line: "さ", n3_oil: 1.59, vitamin_a: 160, mercury: nil, content: "", image: "")
Fish.create!(name: "銀鮭", line: "き", n3_oil: 2.03, vitamin_a: 36, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(白鮭)", line: "さ", n3_oil: 0.92, vitamin_a: 11, mercury: nil, content: "スーパーで売っているスタンダードな鮭", image: "")
Fish.create!(name: "いくら", line: "い", n3_oil: 4.70, vitamin_a: 330, mercury: nil, content: "", image: "")
Fish.create!(name: "ｱﾄﾗﾝﾃｨｯｸｻｰﾓﾝ", line: "あ", n3_oil: 1.94, vitamin_a: 14, mercury: nil, content: "", image: "")
Fish.create!(name: "ﾄﾗｳﾄｻｰﾓﾝ・ﾆｼﾞﾏｽ", line: "と", n3_oil: 2.56, vitamin_a: 57, mercury: nil, content: "", image: "")
Fish.create!(name: "紅鮭", line: "へ", n3_oil: 0.92, vitamin_a: 27, mercury: nil, content: "", image: "")
Fish.create!(name: "ｷﾝｸﾞｻｰﾓﾝ", line: "き", n3_oil: 1.59, vitamin_a: 160, mercury: nil, content: "", image: "")
Fish.create!(name: "さば(ﾏｻﾊﾞ)", line: "さ", n3_oil: 2.12, vitamin_a: 37, mercury: nil, content: "", image: "")
Fish.create!(name: "さば(ｺﾞﾏｻﾞﾊﾞ)", line: "さ", n3_oil: 1.21, vitamin_a: 8, mercury: nil, content: "", image: "")
Fish.create!(name: "さば(ﾉﾙｳｪｰ産)", line: "さ", n3_oil: 6.56, vitamin_a: 44, mercury: nil, content: "", image: "")
Fish.create!(name: "真さば", line: "ま", n3_oil: 2.12, vitamin_a: 37, mercury: nil, content: "", image: "")
Fish.create!(name: "ごまさば", line: "こ", n3_oil: 1.21, vitamin_a: 8, mercury: nil, content: "", image: "")
Fish.create!(name: "クロムツ", line: "く", n3_oil: 0.63, vitamin_a: 8, mercury: 62.5, content: "", image: "")
Fish.create!(name: "コビレゴンドウ", line: "こ", n3_oil: 0, vitamin_a: 250, mercury: nil, content: "", image: "")
Fish.create!(name: "ノルウェーさば", line: "の", n3_oil: 6.56, vitamin_a: 44, mercury: nil, content: "", image: "")
Fish.create!(name: "さば 缶詰", line: "さ", n3_oil: 2.73, vitamin_a: 0, mercury: nil, content: "", image: "")
Fish.create!(name: "さわら", line: "さ", n3_oil: 1.70, vitamin_a: 12, mercury: nil, content: "", image: "")
Fish.create!(name: "さんま", line: "さ", n3_oil: 5.59, vitamin_a: 16, mercury: nil, content: "1匹 80g", image: "")
Fish.create!(name: "ししゃも", line: "し", n3_oil: 1.73, vitamin_a: 120, mercury: nil, content: "1匹 15g", image: "")
Fish.create!(name: "舌平目", line: "し", n3_oil: 0.38, vitamin_a: 30, mercury: nil, content: "", image: "")
Fish.create!(name: "スズキ", line: "す", n3_oil: 0.87, vitamin_a: 180, mercury: nil, content: "", image: "")
Fish.create!(name: "鯛", line: "た", n3_oil: 1.78, vitamin_a: 11, mercury: nil, content: "", image: "")
Fish.create!(name: "まだら(ﾏﾀﾞﾗ)", line: "た", n3_oil: 0.07, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "すけとうだら(ｽｹﾄｳﾀﾞﾗ)", line: "た", n3_oil: 0.25, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "まだら", line: "ま", n3_oil: 0.07, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "すけとうだら", line: "す", n3_oil: 0.25, vitamin_a: 10, mercury: nil, content: "", image: "")
Fish.create!(name: "たらこ", line: "た", n3_oil: 1.19, vitamin_a: 24, mercury: nil, content: "", image: "")
Fish.create!(name: "辛子明太子", line: "か", n3_oil: 1.01, vitamin_a: 41, mercury: nil, content: "", image: "")
Fish.create!(name: "辛子明太子", line: "め", n3_oil: 1.01, vitamin_a: 41, mercury: nil, content: "", image: "")
Fish.create!(name: "にしん", line: "に", n3_oil: 2.13, vitamin_a: 18, mercury: nil, content: "", image: "")
Fish.create!(name: "かずのこ", line: "か", n3_oil: 1.37, vitamin_a: 15, mercury: nil, content: "", image: "")
Fish.create!(name: "ひらめ", line: "ひ", n3_oil: 0.89, vitamin_a: 19, mercury: nil, content: "", image: "")
Fish.create!(name: "フグ", line: "ふ", n3_oil: 0.08, vitamin_a: 3, mercury: nil, content: "", image: "")
Fish.create!(name: "ぶり", line: "ふ", n3_oil: 1.88, vitamin_a: 32, mercury: nil, content: "", image: "")
Fish.create!(name: "ほっけ", line: "ほ", n3_oil: 2.14, vitamin_a: 30, mercury: nil, content: "開き1匹分 200g", image: "")
Fish.create!(name: "マグロ(ｷﾊﾀﾞﾏｸﾞﾛ)", line: "ま", n3_oil: 0.21, vitamin_a: 2, mercury: nil, content: "", image: "")
Fish.create!(name: "マグロ(本ﾏｸﾞﾛ)", line: "ま", n3_oil: 1.87, vitamin_a: 840, mercury: 125, content: "", image: "")
Fish.create!(name: "マグロ(ﾋﾞﾝﾅｶﾞﾏｸﾞﾛ)", line: "ま", n3_oil: 0.21, vitamin_a: 4, mercury: nil, content: "", image: "")
Fish.create!(name: "マグロ(ﾐﾅﾐﾏｸﾞﾛ)", line: "ま", n3_oil: 0.08, vitamin_a: 6, mercury: 62.5, content: "", image: "")
Fish.create!(name: "マグロ(ﾒﾊﾞﾁﾏｸﾞﾛ)", line: "ま", n3_oil: 0.49, vitamin_a: 17, mercury: 125, content: "スーパーで売っているスタンダードなマグロ", image: "")
Fish.create!(name: "キハダマグロ", line: "き", n3_oil: 0.21, vitamin_a: 2, mercury: nil, content: "", image: "")
Fish.create!(name: "本マグロ", line: "ほ", n3_oil: 1.87, vitamin_a: 840, mercury: 125, content: "", image: "")
Fish.create!(name: "ビンナガマグロ", line: "ひ", n3_oil: 0.21, vitamin_a: 4, mercury: nil, content: "", image: "")
Fish.create!(name: "ミナミマグロ", line: "み", n3_oil: 0.08, vitamin_a: 6, mercury: 62.5, content: "", image: "")
Fish.create!(name: "メバチマグロ", line: "め", n3_oil: 0.49, vitamin_a: 17, mercury: 125, content: "スーパーで売っているスタンダードなマグロ", image: "")
Fish.create!(name: "マグロ 缶詰", line: "ま", n3_oil: 1.40, vitamin_a: 8, mercury: nil, content: "", image: "")
Fish.create!(name: "ヨシキリザメ", line: "よ", n3_oil: 0, vitamin_a: 0, mercury: 62.5, content: "", image: "")
Fish.create!(name: "ユメカサゴ", line: "ゆ", n3_oil: 0.28, vitamin_a: 3, mercury: 62.5, content: "", image: "")
Fish.create!(name: "あさり", line: "あ", n3_oil: 0.03, vitamin_a: 22, mercury: nil, content: "1個 3g", image: "")
Fish.create!(name: "アワビ", line: "あ", n3_oil: 0.05, vitamin_a: 1, mercury: nil, content: "1個 50g", image: "")
Fish.create!(name: "ｴｯﾁｭｳﾊﾞｲｶﾞｲ", line: "え", n3_oil: 0, vitamin_a: 0, mercury: 125, content: "", image: "")
Fish.create!(name: "かき", line: "か", n3_oil: 0.52, vitamin_a: 24, mercury: nil, content: "1個 20g", image: "")
Fish.create!(name: "しじみ", line: "し", n3_oil: 0.14, vitamin_a: 33, mercury: nil, content: "1個 1g", image: "")
Fish.create!(name: "はまぐり", line: "は", n3_oil: 0.10, vitamin_a: 9, mercury: nil, content: "1個 15g", image: "")
Fish.create!(name: "帆立", line: "ほ", n3_oil: 0.12, vitamin_a: 23, mercury: nil, content: "貝柱1個 20g", image: "")
Fish.create!(name: "えび(ｱﾏｴﾋﾞ)", line: "え", n3_oil: 0.30, vitamin_a: 3, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "えび(車ｴﾋﾞ)", line: "え", n3_oil: 0.08, vitamin_a: 4, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "えび(桜ｴﾋﾞ)", line: "え", n3_oil: 0.37, vitamin_a: 2, mercury: nil, content: "大さじ1杯 3g", image: "")
Fish.create!(name: "えび(芝ｴﾋﾞ)", line: "え", n3_oil: 0.07, vitamin_a: 4, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "えび(ﾊﾞﾅﾒｲｴﾋﾞ)", line: "え", n3_oil: 0.08, vitamin_a: 0, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "えび(ﾌﾞﾗｯｸﾀｲｶﾞｰ)", line: "え", n3_oil: 0.04, vitamin_a: 1, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "あまえび", line: "あ", n3_oil: 0.30, vitamin_a: 3, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "車えび", line: "く", n3_oil: 0.08, vitamin_a: 4, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "桜えび", line: "さ", n3_oil: 0.37, vitamin_a: 2, mercury: nil, content: "大さじ1杯 3g", image: "")
Fish.create!(name: "芝えび", line: "し", n3_oil: 0.07, vitamin_a: 4, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "バナエイえび", line: "は", n3_oil: 0.08, vitamin_a: 0, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "ブラックタイガー", line: "ふ", n3_oil: 0.04, vitamin_a: 1, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "カニ(ｽﾞﾜｲｶﾞﾆ)", line: "か", n3_oil: 0.11, vitamin_a: 0, mercury: nil, content: "", image: "")
Fish.create!(name: "カニ(ﾀﾗﾊﾞｶﾞﾆ)", line: "か", n3_oil: 0.22, vitamin_a: 1, mercury: nil, content: "", image: "")
Fish.create!(name: "ズワイガニ", line: "す", n3_oil: 0.11, vitamin_a: 0, mercury: nil, content: "", image: "")
Fish.create!(name: "タラバガニ", line: "た", n3_oil: 0.22, vitamin_a: 1, mercury: nil, content: "", image: "")
Fish.create!(name: "イカ(ｽﾙﾒｲｶ)", line: "い", n3_oil: 0.18, vitamin_a: 13, mercury: nil, content: "スーパーで売っているスタンダードなイカ", image: "")
Fish.create!(name: "イカ(ﾎﾀﾙｲｶ)", line: "い", n3_oil: 0.83, vitamin_a: 1500, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "スルメイカ", line: "す", n3_oil: 0.18, vitamin_a: 13, mercury: nil, content: "スーパーで売っているスタンダードなイカ", image: "")
Fish.create!(name: "ホタルイカ", line: "ほ", n3_oil: 0.83, vitamin_a: 1500, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "タコ", line: "た", n3_oil: 0.11, vitamin_a: 5, mercury: nil, content: "", image: "")
Fish.create!(name: "うに", line: "う", n3_oil: 0.73, vitamin_a: 58, mercury: nil, content: "", image: "")
Fish.create!(name: "かにかま", line: "", n3_oil: 0.11, vitamin_a: 21, mercury: nil, content: "1本 10g", image: "")
Fish.create!(name: "かまぼこ", line: "か", n3_oil: 0.21, vitamin_a: 0, mercury: nil, content: "1切 10g", image: "")
Fish.create!(name: "竹輪", line: "ち", n3_oil: 0.20, vitamin_a: 0, mercury: nil, content: "1本 30g", image: "")
Fish.create!(name: "つみれ", line: "つ", n3_oil: 0.71, vitamin_a: 0, mercury: nil, content: "1個 20g", image: "")
Fish.create!(name: "はんぺん", line: "は", n3_oil: 0.08, vitamin_a: 0, mercury: nil, content: "1枚 70g", image: "")
Fish.create!(name: "さつま揚げ", line: "さ", n3_oil: 0.30, vitamin_a: 0, mercury: nil, content: "1枚 50g", image: "")
Fish.create!(name: "魚肉ソーセージ", line: "き", n3_oil: 0.10, vitamin_a: 0, mercury: nil, content: "1本 70g", image: "")
