Fish.create!(name: "赤魚", line: "あ", n3_oil: 0.23, n3_oil_no_data: false, vitamin_a: 26, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "あさり", line: "あ", n3_oil: 0.03, n3_oil_no_data: false, vitamin_a: 22, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 3g", image: "")
Fish.create!(name: "アジ", line: "あ", n3_oil: 1.05, n3_oil_no_data: false, vitamin_a: 7, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 70g", image: "")
Fish.create!(name: "ｱﾄﾗﾝﾃｨｯｸｻｰﾓﾝ", line: "あ", n3_oil: 1.94, n3_oil_no_data: false, vitamin_a: 14, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "穴子", line: "あ", n3_oil: 1.42, n3_oil_no_data: false, vitamin_a: 500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "あまえび", line: "あ", n3_oil: 0.30, n3_oil_no_data: false, vitamin_a: 3, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "アユ", line: "あ", n3_oil: 0.82, n3_oil_no_data: false, vitamin_a: 55, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 80g", image: "")
Fish.create!(name: "アワビ", line: "あ", n3_oil: 0.05, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 50g", image: "")
Fish.create!(name: "あんこう", line: "あ", n3_oil: 0.03, n3_oil_no_data: false, vitamin_a: 13, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "鍋用1片 50g", image: "")
Fish.create!(name: "あんこう 肝", line: "あ", n3_oil: 100, n3_oil_no_data: false, vitamin_a: 8300, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "あん肝1切 20g", image: "")
Fish.create!(name: "イカ(ｽﾙﾒｲｶ)", line: "い", n3_oil: 0.18, n3_oil_no_data: false, vitamin_a: 13, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "スーパーで売っているスタンダードなイカ", image: "")
Fish.create!(name: "イカ(ﾎﾀﾙｲｶ)", line: "い", n3_oil: 0.83, n3_oil_no_data: false, vitamin_a: 1500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "いくら", line: "い", n3_oil: 4.70, n3_oil_no_data: false, vitamin_a: 330, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "イシイルカ", line: "い", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 62.5, content: "", image: "")
Fish.create!(name: "イルカ(ｲｼｲﾙｶ)", line: "い", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 62.5, content: "", image: "")
Fish.create!(name: "イルカ(ﾊﾞﾝﾄﾞｳｲﾙｶ)", line: "い", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 1000, content: "", image: "")
Fish.create!(name: "いわし", line: "い", n3_oil: 2.10, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 50g", image: "")
Fish.create!(name: "いわし 缶詰", line: "い", n3_oil: 2.92, n3_oil_no_data: false, vitamin_a: 9, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "うなぎ", line: "う", n3_oil: 2.87, n3_oil_no_data: false, vitamin_a:1500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "蒲焼1切 50g", image: "")
Fish.create!(name: "うなぎ 肝", line: "う", n3_oil: 0.79, n3_oil_no_data: false, vitamin_a: 4400, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 10g", image: "")
Fish.create!(name: "うに", line: "う", n3_oil: 0.73, n3_oil_no_data: false, vitamin_a: 58, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "ｴｯﾁｭｳﾊﾞｲｶﾞｲ", line: "え", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 125, content: "", image: "")
Fish.create!(name: "えび(ｱﾏｴﾋﾞ)", line: "え", n3_oil: 0.30, n3_oil_no_data: false, vitamin_a: 3, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "えび(車ｴﾋﾞ)", line: "え", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "えび(桜ｴﾋﾞ)", line: "え", n3_oil: 0.37, n3_oil_no_data: false, vitamin_a: 2, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "大さじ1杯 3g", image: "")
Fish.create!(name: "えび(芝ｴﾋﾞ)", line: "え", n3_oil: 0.07, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "えび(ﾊﾞﾅﾒｲｴﾋﾞ)", line: "え", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "えび(ﾌﾞﾗｯｸﾀｲｶﾞｰ)", line: "え", n3_oil: 0.04, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "かき", line: "か", n3_oil: 0.52, n3_oil_no_data: false, vitamin_a: 24, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 20g", image: "")
Fish.create!(name: "カジキ(ﾏｶｼﾞｷ)", line: "か", n3_oil: 0.44, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "高級魚。スーパーでは「メカジキ」の方が多い", image: "")
Fish.create!(name: "カジキ(ﾒｶｼﾞｷ)", line: "か", n3_oil: 0.92, n3_oil_no_data: false, vitamin_a: 61, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "かずのこ", line: "か", n3_oil: 1.37, n3_oil_no_data: false, vitamin_a: 15, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "かつお(春獲り)", line: "か", n3_oil: 0.17, n3_oil_no_data: false, vitamin_a: 5, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "かつお(秋獲り)", line: "か", n3_oil: 1.57, n3_oil_no_data: false, vitamin_a: 20, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "かつお 缶詰", line: "か", n3_oil: 1.99,  n3_oil_no_data: false,vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "カニ(ｽﾞﾜｲｶﾞﾆ)", line: "か", n3_oil: 0.11, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "カニ(ﾀﾗﾊﾞｶﾞﾆ)", line: "か", n3_oil: 0.22, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "かにかま", line: "か", n3_oil: 0.11, n3_oil_no_data: false, vitamin_a: 21, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1本 10g", image: "")
Fish.create!(name: "かまぼこ", line: "か", n3_oil: 0.21, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1切 10g", image: "")
Fish.create!(name: "辛子明太子", line: "か", n3_oil: 1.01, n3_oil_no_data: false, vitamin_a: 41, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "かれい", line: "か", n3_oil: 0.35, n3_oil_no_data: false, vitamin_a: 5, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "カンパチ", line: "か", n3_oil: 1.07, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "きす", line: "き", n3_oil: 0.05, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "キダイ", line: "き", n3_oil: 0.57, n3_oil_no_data: false, vitamin_a: 50, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "キハダマグロ", line: "き", n3_oil: 0.21, n3_oil_no_data: false, vitamin_a: 2, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "魚肉ソーセージ", line: "き", n3_oil: 0.10, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1本 70g", image: "")
Fish.create!(name: "銀鮭", line: "き", n3_oil: 2.03, n3_oil_no_data: false, vitamin_a: 36, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "キングサーモン", line: "き", n3_oil: 1.59, n3_oil_no_data: false, vitamin_a: 160, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "銀だら", line: "き", n3_oil: 1.13, n3_oil_no_data: false, vitamin_a: 1500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "金目鯛", line: "き", n3_oil: 1.37, n3_oil_no_data: false, vitamin_a: 63, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "クジラ(ﾂﾁｸｼﾞﾗ)", line: "く", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 125, content: "", image: "")
Fish.create!(name: "クジラ(ﾏｯｺｳｸｼﾞﾗ)", line: "く", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 125, content: "", image: "")
Fish.create!(name: "車えび", line: "く", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "クロムツ", line: "く", n3_oil: 0.63, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "コビレゴンドウ", line: "こ", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 250, content: "", image: "")
Fish.create!(name: "ごまさば", line: "こ", n3_oil: 1.21, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "桜えび", line: "さ", n3_oil: 0.37, n3_oil_no_data: false, vitamin_a: 2, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "大さじ1杯 3g", image: "")
Fish.create!(name: "鮭(ｱﾄﾗﾝﾃｨｯｸｻｰﾓﾝ)", line: "さ", n3_oil: 1.94, n3_oil_no_data: false, vitamin_a: 14, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(ｷﾝｸﾞｻｰﾓﾝ)", line: "さ", n3_oil: 1.59, n3_oil_no_data: false, vitamin_a: 160, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(銀鮭)", line: "さ", n3_oil: 2.03, n3_oil_no_data: false, vitamin_a: 36, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(白鮭)", line: "さ", n3_oil: 0.92, n3_oil_no_data: false, vitamin_a: 11, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "スーパーで売っているスタンダードな鮭", image: "")
Fish.create!(name: "鮭(ﾄﾗｳﾄｻｰﾓﾝ・ﾆｼﾞﾏｽ)", line: "さ", n3_oil: 2.56, n3_oil_no_data: false, vitamin_a: 57, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "鮭(紅鮭)", line: "さ", n3_oil: 0.92, n3_oil_no_data: false, vitamin_a: 27, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "さつま揚げ", line: "さ", n3_oil: 0.30, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1枚 50g", image: "")
Fish.create!(name: "さば(ｺﾞﾏｻﾞﾊﾞ)", line: "さ", n3_oil: 1.21, n3_oil_no_data: false, vitamin_a: 8,  vitamin_a_tr: false, vitamin_a_no_data: false,mercury: nil, content: "", image: "")
Fish.create!(name: "さば(ﾉﾙｳｪｰ産)", line: "さ", n3_oil: 6.56, n3_oil_no_data: false, vitamin_a: 44, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "さば(ﾏｻﾊﾞ)", line: "さ", n3_oil: 2.12, n3_oil_no_data: false, vitamin_a: 37, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "さば 缶詰", line: "さ", n3_oil: 2.73, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "さわら", line: "さ", n3_oil: 1.70, n3_oil_no_data: false, vitamin_a: 12, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "さんま", line: "さ", n3_oil: 5.59, n3_oil_no_data: false, vitamin_a: 16, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 80g", image: "")
Fish.create!(name: "しじみ", line: "し", n3_oil: 0.14, n3_oil_no_data: false,vitamin_a: 33, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 1g", image: "")
Fish.create!(name: "ししゃも", line: "し", n3_oil: 1.73, n3_oil_no_data: false, vitamin_a: 120, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 15g", image: "")
Fish.create!(name: "舌平目", line: "し", n3_oil: 0.38, n3_oil_no_data: false, vitamin_a: 30, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "芝えび", line: "し", n3_oil: 0.07, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 5g", image: "")
Fish.create!(name: "しらす", line: "し", n3_oil: 0.49, n3_oil_no_data: false, vitamin_a: 140, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "すけとうだら", line: "す", n3_oil: 0.25, n3_oil_no_data: false, vitamin_a: 10, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "スズキ", line: "す", n3_oil: 0.87, n3_oil_no_data: false, vitamin_a: 180, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "スルメイカ", line: "す", n3_oil: 0.18, n3_oil_no_data: false, vitamin_a: 13, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "スーパーで売っているスタンダードなイカ", image: "")
Fish.create!(name: "ズワイガニ", line: "す", n3_oil: 0.11, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "鯛(ｷﾀﾞｲ)", line: "た", n3_oil: 0.57, n3_oil_no_data: false, vitamin_a: 50, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "鯛(ｷﾝﾒﾀﾞｲ)", line: "た", n3_oil: 1.37, n3_oil_no_data: false, vitamin_a: 63, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "鯛(ﾏﾀﾞｲ)", line: "た", n3_oil: 1.78,  n3_oil_no_data: false,vitamin_a: 11, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "スタンダードな鯛", image: "")
Fish.create!(name: "タコ", line: "た", n3_oil: 0.11, n3_oil_no_data: false, vitamin_a: 5, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(銀ﾀﾞﾗ)", line: "た", n3_oil: 1.13, n3_oil_no_data: false, vitamin_a: 1500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(ｽｹﾄｳﾀﾞﾗ)", line: "た", n3_oil: 0.25, n3_oil_no_data: false, vitamin_a: 10, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "たら(ﾏﾀﾞﾗ)", line: "た", n3_oil: 0.07, n3_oil_no_data: false, vitamin_a: 10, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "たらこ", line: "た", n3_oil: 1.19, n3_oil_no_data: false, vitamin_a: 24, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "タラバガニ", line: "た", n3_oil: 0.22, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "竹輪", line: "ち", n3_oil: 0.20, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1本 30g", image: "")
Fish.create!(name: "ツチクジラ", line: "つ", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 125, content: "", image: "")
Fish.create!(name: "ツナ缶(ｶﾂｵ)", line: "つ", n3_oil: 1.99,  n3_oil_no_data: false,vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "ツナ缶(ﾏｸﾞﾛ)", line: "つ", n3_oil: 1.40, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "つみれ", line: "つ", n3_oil: 0.71, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1個 20g", image: "")
Fish.create!(name: "ﾄﾗｳﾄｻｰﾓﾝ・ﾆｼﾞﾏｽ", line: "と", n3_oil: 2.56, n3_oil_no_data: false, vitamin_a: 57, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "にしん", line: "に", n3_oil: 2.13, n3_oil_no_data: false, vitamin_a: 18, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "バナエイえび", line: "は", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "はまぐり", line: "は", n3_oil: 0.10, n3_oil_no_data: false, vitamin_a: 9, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1個 15g", image: "")
Fish.create!(name: "バンドウイルカ", line: "は", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 1000, content: "", image: "")
Fish.create!(name: "はんぺん", line: "は", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 0, vitamin_a_tr: true, vitamin_a_no_data: false, mercury: nil, content: "1枚 70g", image: "")
Fish.create!(name: "ひらめ", line: "ひ", n3_oil: 0.89, n3_oil_no_data: false, vitamin_a: 19, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "ビンナガマグロ", line: "ひ", n3_oil: 0.21, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "フグ", line: "ふ", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 3, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "ブラックタイガー", line: "ふ", n3_oil: 0.04, n3_oil_no_data: false, vitamin_a: 1, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 20g", image: "")
Fish.create!(name: "ぶり", line: "ふ", n3_oil: 1.88, n3_oil_no_data: false, vitamin_a: 32, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "紅鮭", line: "へ", n3_oil: 0.92, n3_oil_no_data: false, vitamin_a: 27, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "帆立", line: "ほ", n3_oil: 0.12, n3_oil_no_data: false, vitamin_a: 23, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "貝柱1個 20g", image: "")
Fish.create!(name: "ホタルイカ", line: "ほ", n3_oil: 0.83, n3_oil_no_data: false, vitamin_a: 1500, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "1匹 10g", image: "")
Fish.create!(name: "ほっけ", line: "ほ", n3_oil: 2.14, n3_oil_no_data: false, vitamin_a: 30, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "開き1匹分 200g", image: "")
Fish.create!(name: "本マグロ", line: "ほ", n3_oil: 1.87, n3_oil_no_data: false, vitamin_a: 840, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "マカジキ", line: "ま", n3_oil: 0.44, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "高級魚。スーパーでは「メカジキ」の方が多い", image: "")
Fish.create!(name: "マグロ(ｷﾊﾀﾞﾏｸﾞﾛ)", line: "ま", n3_oil: 0.21, n3_oil_no_data: false, vitamin_a: 2, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "マグロ(ﾋﾞﾝﾅｶﾞﾏｸﾞﾛ)", line: "ま", n3_oil: 0.21, n3_oil_no_data: false, vitamin_a: 4, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "マグロ(本ﾏｸﾞﾛ)", line: "ま", n3_oil: 1.87, n3_oil_no_data: false, vitamin_a: 840, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "マグロ(ﾐﾅﾐﾏｸﾞﾛ)", line: "ま", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 6, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "マグロ(ﾒﾊﾞﾁﾏｸﾞﾛ)", line: "ま", n3_oil: 0.49, n3_oil_no_data: false, vitamin_a: 17, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "スーパーで売っているスタンダードなマグロ", image: "")
Fish.create!(name: "マグロ 缶詰", line: "ま", n3_oil: 1.40, n3_oil_no_data: false, vitamin_a: 8, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "真さば", line: "ま", n3_oil: 2.12, n3_oil_no_data: false, vitamin_a: 37, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "まだら", line: "ま", n3_oil: 0.07, n3_oil_no_data: false, vitamin_a: 10, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: nil, content: "", image: "")
Fish.create!(name: "マッコウクジラ", line: "ま", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 125, content: "", image: "")
Fish.create!(name: "ミナミマグロ", line: "み", n3_oil: 0.08, n3_oil_no_data: false, vitamin_a: 6, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "メカジキ", line: "め", n3_oil: 0.92, n3_oil_no_data: false, vitamin_a: 61, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "", image: "")
Fish.create!(name: "メバチマグロ", line: "め", n3_oil: 0.49, n3_oil_no_data: false, vitamin_a: 17, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 125, content: "スーパーで売っているスタンダードなマグロ", image: "")
Fish.create!(name: "ユメカサゴ", line: "ゆ", n3_oil: 0.28, n3_oil_no_data: false, vitamin_a: 3, vitamin_a_tr: false, vitamin_a_no_data: false, mercury: 62.5, content: "", image: "")
Fish.create!(name: "ヨシキリザメ", line: "よ", n3_oil: 0, n3_oil_no_data: true, vitamin_a: 0, vitamin_a_tr: false, vitamin_a_no_data: true, mercury: 62.5, content: "", image: "")

User.create!(name: "つな子001", email: nil, password: "000000", admin: true, baby_due_on: "")
User.create!(name: "たら子001", email: nil, password: "000000", admin: true, baby_due_on: "2021-12-01")
User.create!(name: "あゆ美001", email: nil, password: "000000", admin: true, baby_due_on: "2021-08-30")
User.create!(name: "つな子002", email: nil, password: "000000", admin: false, baby_due_on: "")
User.create!(name: "たら子002", email: nil, password: "000000", admin: false, baby_due_on: "2021-12-01")
User.create!(name: "あゆ美002", email: nil, password: "000000", admin: false, baby_due_on: "2021-08-30")

Favorite.create(user_id: "1", fish_id:"10")
Favorite.create(user_id: "1", fish_id:"20")
Favorite.create(user_id: "1", fish_id:"30")
Favorite.create(user_id: "1", fish_id:"40")
Favorite.create(user_id: "1", fish_id:"50")

Diary.create!(amount: 100, input_at: "2021-08-11 00:00:00", user_id: 1, fish_id: 2,)
Diary.create!(amount: 50, input_at: "2021-08-11 00:00:00", user_id: 1, fish_id: 5,)
Diary.create!(amount: 80, input_at: "2021-08-13 00:00:00", user_id: 2, fish_id: 10,)
Diary.create!(amount: 80, input_at: "2021-08-09 00:00:00", user_id: 2, fish_id: 50,)
Diary.create!(amount: 150, input_at: "2021-08-09 00:00:00", user_id: 2, fish_id: 8,)
